### ISSUE TITLE
[ERROR] "Failed to create tables in the database" displays when searching

### ISSUE THREAD

**Issue by devfromthebar** [kodejuice/localGoogoo#3]
Hi! First of all, thank you for this amazing tool.

I was able to display http://localhost/localgoogoo/index.php, but when I search something, or click the "Manage Indexed Websites", the error displays:

_Failed to create tables in the database_

_Specified key was too long; max key length is 1000 bytes_

What can I do to fix this?

**Comment by kodejuice** [comment]
The latest commit should fix this, it probably was a problem with storage engine used `MyISAM`, now its switched to `InnoDB`.
Update the repo and test if it works

**Comment by devfromthebar** [comment]
It works! Thank you! 👍
